GRANT USAGE ON SCHEMA public TO orchestra_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO orchestra_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO orchestra_app;

GRANT USAGE ON SCHEMA public TO orchestra_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO orchestra_admin;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO orchestra_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO orchestra_app, orchestra_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO orchestra_app, orchestra_admin;
